on:
  workflow_dispatch:
jobs:
  artifact:

    runs-on:  ubuntu-latest
    if:  always()
    steps:
      - uses:  actions/checkout@v3
        with:
          repository:   tldr-pages/tldr-python-client
          ref:  "3.1.0"
      - uses:  actions/setup-python@v3
        with:
          python-version: "3.10"
      - run:  pip install -r requirements.txt
      - run:  |
            pip install pytest
            pip install pytest-html
      - name:  "execute test"
        run: python -m pytest --html=report.html --self-contained-html
      - name:  save the report
        if:  always()
        uses:  actions/upload-artifact@v3
        with:
          name:  pytest-report
          path:  report.html

      

